// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/fastly-test-go/v2/models/components"
	"net/http"
)

type BulkUpdateConfigStoreItemRequest struct {
	BulkUpdateConfigStoreListRequest *components.BulkUpdateConfigStoreListRequest `request:"mediaType=application/json"`
	// An alphanumeric string identifying the config store.
	ConfigStoreID string `pathParam:"style=simple,explode=false,name=config_store_id"`
}

func (o *BulkUpdateConfigStoreItemRequest) GetBulkUpdateConfigStoreListRequest() *components.BulkUpdateConfigStoreListRequest {
	if o == nil {
		return nil
	}
	return o.BulkUpdateConfigStoreListRequest
}

func (o *BulkUpdateConfigStoreItemRequest) GetConfigStoreID() string {
	if o == nil {
		return ""
	}
	return o.ConfigStoreID
}

// BulkUpdateConfigStoreItemResponseBody - OK
type BulkUpdateConfigStoreItemResponseBody struct {
	// ok
	Status *string `json:"status,omitempty"`
}

func (o *BulkUpdateConfigStoreItemResponseBody) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type BulkUpdateConfigStoreItemResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *BulkUpdateConfigStoreItemResponseBody
}

func (o *BulkUpdateConfigStoreItemResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BulkUpdateConfigStoreItemResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BulkUpdateConfigStoreItemResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *BulkUpdateConfigStoreItemResponse) GetObject() *BulkUpdateConfigStoreItemResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
