// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/models/components"
	"net/http"
)

type CreateLogNewrelicRequest struct {
	LoggingNewrelic *components.LoggingNewrelic `request:"mediaType=application/x-www-form-urlencoded"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *CreateLogNewrelicRequest) GetLoggingNewrelic() *components.LoggingNewrelic {
	if o == nil {
		return nil
	}
	return o.LoggingNewrelic
}

func (o *CreateLogNewrelicRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *CreateLogNewrelicRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type CreateLogNewrelicResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	LoggingNewrelicResponse *components.LoggingNewrelicResponse
}

func (o *CreateLogNewrelicResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLogNewrelicResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLogNewrelicResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateLogNewrelicResponse) GetLoggingNewrelicResponse() *components.LoggingNewrelicResponse {
	if o == nil {
		return nil
	}
	return o.LoggingNewrelicResponse
}
