// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteLogHerokuRequest struct {
	// The name for the real-time logging configuration.
	LoggingHerokuName string `pathParam:"style=simple,explode=false,name=logging_heroku_name"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *DeleteLogHerokuRequest) GetLoggingHerokuName() string {
	if o == nil {
		return ""
	}
	return o.LoggingHerokuName
}

func (o *DeleteLogHerokuRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *DeleteLogHerokuRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

// DeleteLogHerokuResponseBody - OK
type DeleteLogHerokuResponseBody struct {
	// ok
	Status *string `json:"status,omitempty"`
}

func (o *DeleteLogHerokuResponseBody) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteLogHerokuResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *DeleteLogHerokuResponseBody
}

func (o *DeleteLogHerokuResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteLogHerokuResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteLogHerokuResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteLogHerokuResponse) GetObject() *DeleteLogHerokuResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
