// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ListRolePermissionsRequest struct {
	// Alphanumeric string identifying the role.
	RoleID string `pathParam:"style=simple,explode=false,name=role_id"`
}

func (o *ListRolePermissionsRequest) GetRoleID() string {
	if o == nil {
		return ""
	}
	return o.RoleID
}

// ListRolePermissionsResponseBody - OK
type ListRolePermissionsResponseBody struct {
}

type ListRolePermissionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	Object *ListRolePermissionsResponseBody
}

func (o *ListRolePermissionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListRolePermissionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListRolePermissionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ListRolePermissionsResponse) GetObject() *ListRolePermissionsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
