// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/fastly-test-go/v2/models/components"
	"net/http"
)

type PatchMutualAuthenticationRequest struct {
	MutualAuthentication *components.MutualAuthentication `request:"mediaType=application/vnd.api+json"`
	// Alphanumeric string identifying a mutual authentication.
	MutualAuthenticationID string `pathParam:"style=simple,explode=false,name=mutual_authentication_id"`
}

func (o *PatchMutualAuthenticationRequest) GetMutualAuthentication() *components.MutualAuthentication {
	if o == nil {
		return nil
	}
	return o.MutualAuthentication
}

func (o *PatchMutualAuthenticationRequest) GetMutualAuthenticationID() string {
	if o == nil {
		return ""
	}
	return o.MutualAuthenticationID
}

type PatchMutualAuthenticationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	MutualAuthenticationResponse *components.MutualAuthenticationResponse
}

func (o *PatchMutualAuthenticationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchMutualAuthenticationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchMutualAuthenticationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchMutualAuthenticationResponse) GetMutualAuthenticationResponse() *components.MutualAuthenticationResponse {
	if o == nil {
		return nil
	}
	return o.MutualAuthenticationResponse
}
