// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/fastly-test-go/models/components"
	"net/http"
)

type UpdateTLSActivationRequest struct {
	TLSActivation *components.TLSActivation `request:"mediaType=application/vnd.api+json"`
	// Alphanumeric string identifying a TLS activation.
	TLSActivationID string `pathParam:"style=simple,explode=false,name=tls_activation_id"`
}

func (o *UpdateTLSActivationRequest) GetTLSActivation() *components.TLSActivation {
	if o == nil {
		return nil
	}
	return o.TLSActivation
}

func (o *UpdateTLSActivationRequest) GetTLSActivationID() string {
	if o == nil {
		return ""
	}
	return o.TLSActivationID
}

type UpdateTLSActivationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	TLSActivationResponse *components.TLSActivationResponse
}

func (o *UpdateTLSActivationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateTLSActivationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateTLSActivationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateTLSActivationResponse) GetTLSActivationResponse() *components.TLSActivationResponse {
	if o == nil {
		return nil
	}
	return o.TLSActivationResponse
}
