// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/models/components"
	"net/http"
)

type UpsertConfigStoreItemRequest struct {
	// An alphanumeric string identifying the config store.
	ConfigStoreID   string                      `pathParam:"style=simple,explode=false,name=config_store_id"`
	ConfigStoreItem *components.ConfigStoreItem `request:"mediaType=application/x-www-form-urlencoded"`
	// Item key, maximum 256 characters.
	ConfigStoreItemKey string `pathParam:"style=simple,explode=false,name=config_store_item_key"`
}

func (o *UpsertConfigStoreItemRequest) GetConfigStoreID() string {
	if o == nil {
		return ""
	}
	return o.ConfigStoreID
}

func (o *UpsertConfigStoreItemRequest) GetConfigStoreItem() *components.ConfigStoreItem {
	if o == nil {
		return nil
	}
	return o.ConfigStoreItem
}

func (o *UpsertConfigStoreItemRequest) GetConfigStoreItemKey() string {
	if o == nil {
		return ""
	}
	return o.ConfigStoreItemKey
}

type UpsertConfigStoreItemResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ConfigStoreItemResponse *components.ConfigStoreItemResponse
}

func (o *UpsertConfigStoreItemResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpsertConfigStoreItemResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpsertConfigStoreItemResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpsertConfigStoreItemResponse) GetConfigStoreItemResponse() *components.ConfigStoreItemResponse {
	if o == nil {
		return nil
	}
	return o.ConfigStoreItemResponse
}
