// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/fastly-test-go/v2/internal/utils"
)

// BulkWafActiveRuleStatus - Describes the behavior for the particular rule revision within this firewall version.
type BulkWafActiveRuleStatus string

const (
	BulkWafActiveRuleStatusLog   BulkWafActiveRuleStatus = "log"
	BulkWafActiveRuleStatusBlock BulkWafActiveRuleStatus = "block"
	BulkWafActiveRuleStatusScore BulkWafActiveRuleStatus = "score"
)

func (e BulkWafActiveRuleStatus) ToPointer() *BulkWafActiveRuleStatus {
	return &e
}

func (e *BulkWafActiveRuleStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "log":
		fallthrough
	case "block":
		fallthrough
	case "score":
		*e = BulkWafActiveRuleStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BulkWafActiveRuleStatus: %v", v)
	}
}

type Attributes struct {
	// The ModSecurity rule ID of the associated rule revision.
	ModsecRuleID *int64                   `json:"modsec_rule_id,omitempty"`
	Revision     *WafRuleRevisionOrLatest `json:"revision,omitempty"`
	// Describes the behavior for the particular rule revision within this firewall version.
	Status *BulkWafActiveRuleStatus `json:"status,omitempty"`
}

func (o *Attributes) GetModsecRuleID() *int64 {
	if o == nil {
		return nil
	}
	return o.ModsecRuleID
}

func (o *Attributes) GetRevision() *WafRuleRevisionOrLatest {
	if o == nil {
		return nil
	}
	return o.Revision
}

func (o *Attributes) GetStatus() *BulkWafActiveRuleStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type BulkWafActiveRule struct {
	Attributes    *Attributes                         `json:"attributes,omitempty"`
	Relationships *RelationshipsForWafActiveRuleInput `json:"relationships,omitempty"`
	// Resource type.
	Type *TypeWafActiveRule `default:"waf_active_rule" json:"type"`
}

func (b BulkWafActiveRule) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkWafActiveRule) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *BulkWafActiveRule) GetAttributes() *Attributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *BulkWafActiveRule) GetRelationships() *RelationshipsForWafActiveRuleInput {
	if o == nil {
		return nil
	}
	return o.Relationships
}

func (o *BulkWafActiveRule) GetType() *TypeWafActiveRule {
	if o == nil {
		return nil
	}
	return o.Type
}
