// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// LoggingUseTLS - Whether to use TLS.
type LoggingUseTLS int64

const (
	LoggingUseTLSZero LoggingUseTLS = 0
	LoggingUseTLSOne  LoggingUseTLS = 1
)

func (e LoggingUseTLS) ToPointer() *LoggingUseTLS {
	return &e
}

func (e *LoggingUseTLS) UnmarshalJSON(data []byte) error {
	var v int64
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case 0:
		fallthrough
	case 1:
		*e = LoggingUseTLS(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LoggingUseTLS: %v", v)
	}
}
