// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

// PublishRequest - Contains a batch of messages to publish.
type PublishRequest struct {
	// The messages to publish.
	Items []PublishItem `json:"items"`
}

func (o *PublishRequest) GetItems() []PublishItem {
	if o == nil {
		return []PublishItem{}
	}
	return o.Items
}
