// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type TLSSubscriptions struct {
	Data []RelationshipMemberTLSSubscription `json:"data,omitempty"`
}

func (o *TLSSubscriptions) GetData() []RelationshipMemberTLSSubscription {
	if o == nil {
		return nil
	}
	return o.Data
}

type RelationshipTLSSubscriptions struct {
	TLSSubscriptions *TLSSubscriptions `json:"tls_subscriptions,omitempty"`
}

func (o *RelationshipTLSSubscriptions) GetTLSSubscriptions() *TLSSubscriptions {
	if o == nil {
		return nil
	}
	return o.TLSSubscriptions
}
