// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type WafTags struct {
	Data []RelationshipMemberWafTag `json:"data,omitempty"`
}

func (o *WafTags) GetData() []RelationshipMemberWafTag {
	if o == nil {
		return nil
	}
	return o.Data
}

type RelationshipWafTags struct {
	WafTags *WafTags `json:"waf_tags,omitempty"`
}

func (o *RelationshipWafTags) GetWafTags() *WafTags {
	if o == nil {
		return nil
	}
	return o.WafTags
}
