// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

type TLSDomains struct {
	Data []RelationshipMemberTLSDomain `json:"data,omitempty"`
}

func (o *TLSDomains) GetData() []RelationshipMemberTLSDomain {
	if o == nil {
		return nil
	}
	return o.Data
}

type RelationshipTLSDomains struct {
	TLSDomains *TLSDomains `json:"tls_domains,omitempty"`
}

func (o *RelationshipTLSDomains) GetTLSDomains() *TLSDomains {
	if o == nil {
		return nil
	}
	return o.TLSDomains
}
