// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"github.com/speakeasy-sdks/fastly-test-go/internal/utils"
)

type SchemasWafFirewallVersionDataAttributes struct {
	// Allowed HTTP versions.
	AllowedHTTPVersions *string `default:"HTTP/1.0 HTTP/1.1 HTTP/2" json:"allowed_http_versions"`
	// A space-separated list of HTTP method names.
	AllowedMethods *string `default:"GET HEAD POST OPTIONS PUT PATCH DELETE" json:"allowed_methods"`
	// Allowed request content types.
	AllowedRequestContentType *string `default:"application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|text/plain" json:"allowed_request_content_type"`
	// Allowed request content type charset.
	AllowedRequestContentTypeCharset *string `default:"utf-8|iso-8859-1|iso-8859-15|windows-1252" json:"allowed_request_content_type_charset"`
	// The maximum allowed length of an argument.
	ArgLength *int64 `default:"400" json:"arg_length"`
	// The maximum allowed argument name length.
	ArgNameLength *int64 `default:"100" json:"arg_name_length"`
	// The maximum allowed size of all files (in bytes).
	CombinedFileSizes *int64 `default:"10000000" json:"combined_file_sizes"`
	// A freeform descriptive note.
	Comment *string `json:"comment,omitempty"`
	// Score value to add for critical anomalies.
	CriticalAnomalyScore *int64 `default:"6" json:"critical_anomaly_score"`
	// CRS validate UTF8 encoding.
	CrsValidateUTF8Encoding *bool `json:"crs_validate_utf8_encoding,omitempty"`
	// Score value to add for error anomalies.
	ErrorAnomalyScore *int64 `default:"5" json:"error_anomaly_score"`
	// A space-separated list of country codes in ISO 3166-1 (two-letter) format.
	HighRiskCountryCodes *string `json:"high_risk_country_codes,omitempty"`
	// HTTP violation threshold.
	HTTPViolationScoreThreshold *int64 `json:"http_violation_score_threshold,omitempty"`
	// Inbound anomaly threshold.
	InboundAnomalyScoreThreshold *int64 `json:"inbound_anomaly_score_threshold,omitempty"`
	// Local file inclusion attack threshold.
	LfiScoreThreshold *int64 `json:"lfi_score_threshold,omitempty"`
	// Whether a specific firewall version is locked from being modified.
	Locked *bool `default:"false" json:"locked"`
	// The maximum allowed file size, in bytes.
	MaxFileSize *int64 `default:"10000000" json:"max_file_size"`
	// The maximum number of arguments allowed.
	MaxNumArgs *int64 `default:"255" json:"max_num_args"`
	// Score value to add for notice anomalies.
	NoticeAnomalyScore *int64 `default:"4" json:"notice_anomaly_score"`
	Number             *int64 `json:"number,omitempty"`
	// The configured paranoia level.
	ParanoiaLevel *int64 `default:"1" json:"paranoia_level"`
	// PHP injection threshold.
	PhpInjectionScoreThreshold *int64 `json:"php_injection_score_threshold,omitempty"`
	// Remote code execution threshold.
	RceScoreThreshold *int64 `json:"rce_score_threshold,omitempty"`
	// A space-separated list of allowed file extensions.
	RestrictedExtensions *string `default:".asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .resources/ .resx/ .sql/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx" json:"restricted_extensions"`
	// A space-separated list of allowed header names.
	RestrictedHeaders *string `default:"/proxy/ /lock-token/ /content-range/ /translate/ /if/" json:"restricted_headers"`
	// Remote file inclusion attack threshold.
	RfiScoreThreshold *int64 `json:"rfi_score_threshold,omitempty"`
	// Session fixation attack threshold.
	SessionFixationScoreThreshold *int64 `json:"session_fixation_score_threshold,omitempty"`
	// SQL injection attack threshold.
	SQLInjectionScoreThreshold *int64 `json:"sql_injection_score_threshold,omitempty"`
	// The maximum size of argument names and values.
	TotalArgLength *int64 `default:"6400" json:"total_arg_length"`
	// Score value to add for warning anomalies.
	WarningAnomalyScore *int64 `json:"warning_anomaly_score,omitempty"`
	// XSS attack threshold.
	XSSScoreThreshold *int64 `json:"xss_score_threshold,omitempty"`
}

func (s SchemasWafFirewallVersionDataAttributes) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasWafFirewallVersionDataAttributes) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SchemasWafFirewallVersionDataAttributes) GetAllowedHTTPVersions() *string {
	if o == nil {
		return nil
	}
	return o.AllowedHTTPVersions
}

func (o *SchemasWafFirewallVersionDataAttributes) GetAllowedMethods() *string {
	if o == nil {
		return nil
	}
	return o.AllowedMethods
}

func (o *SchemasWafFirewallVersionDataAttributes) GetAllowedRequestContentType() *string {
	if o == nil {
		return nil
	}
	return o.AllowedRequestContentType
}

func (o *SchemasWafFirewallVersionDataAttributes) GetAllowedRequestContentTypeCharset() *string {
	if o == nil {
		return nil
	}
	return o.AllowedRequestContentTypeCharset
}

func (o *SchemasWafFirewallVersionDataAttributes) GetArgLength() *int64 {
	if o == nil {
		return nil
	}
	return o.ArgLength
}

func (o *SchemasWafFirewallVersionDataAttributes) GetArgNameLength() *int64 {
	if o == nil {
		return nil
	}
	return o.ArgNameLength
}

func (o *SchemasWafFirewallVersionDataAttributes) GetCombinedFileSizes() *int64 {
	if o == nil {
		return nil
	}
	return o.CombinedFileSizes
}

func (o *SchemasWafFirewallVersionDataAttributes) GetComment() *string {
	if o == nil {
		return nil
	}
	return o.Comment
}

func (o *SchemasWafFirewallVersionDataAttributes) GetCriticalAnomalyScore() *int64 {
	if o == nil {
		return nil
	}
	return o.CriticalAnomalyScore
}

func (o *SchemasWafFirewallVersionDataAttributes) GetCrsValidateUTF8Encoding() *bool {
	if o == nil {
		return nil
	}
	return o.CrsValidateUTF8Encoding
}

func (o *SchemasWafFirewallVersionDataAttributes) GetErrorAnomalyScore() *int64 {
	if o == nil {
		return nil
	}
	return o.ErrorAnomalyScore
}

func (o *SchemasWafFirewallVersionDataAttributes) GetHighRiskCountryCodes() *string {
	if o == nil {
		return nil
	}
	return o.HighRiskCountryCodes
}

func (o *SchemasWafFirewallVersionDataAttributes) GetHTTPViolationScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.HTTPViolationScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetInboundAnomalyScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.InboundAnomalyScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetLfiScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.LfiScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetLocked() *bool {
	if o == nil {
		return nil
	}
	return o.Locked
}

func (o *SchemasWafFirewallVersionDataAttributes) GetMaxFileSize() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxFileSize
}

func (o *SchemasWafFirewallVersionDataAttributes) GetMaxNumArgs() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxNumArgs
}

func (o *SchemasWafFirewallVersionDataAttributes) GetNoticeAnomalyScore() *int64 {
	if o == nil {
		return nil
	}
	return o.NoticeAnomalyScore
}

func (o *SchemasWafFirewallVersionDataAttributes) GetNumber() *int64 {
	if o == nil {
		return nil
	}
	return o.Number
}

func (o *SchemasWafFirewallVersionDataAttributes) GetParanoiaLevel() *int64 {
	if o == nil {
		return nil
	}
	return o.ParanoiaLevel
}

func (o *SchemasWafFirewallVersionDataAttributes) GetPhpInjectionScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.PhpInjectionScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetRceScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.RceScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetRestrictedExtensions() *string {
	if o == nil {
		return nil
	}
	return o.RestrictedExtensions
}

func (o *SchemasWafFirewallVersionDataAttributes) GetRestrictedHeaders() *string {
	if o == nil {
		return nil
	}
	return o.RestrictedHeaders
}

func (o *SchemasWafFirewallVersionDataAttributes) GetRfiScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.RfiScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetSessionFixationScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.SessionFixationScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetSQLInjectionScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.SQLInjectionScoreThreshold
}

func (o *SchemasWafFirewallVersionDataAttributes) GetTotalArgLength() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalArgLength
}

func (o *SchemasWafFirewallVersionDataAttributes) GetWarningAnomalyScore() *int64 {
	if o == nil {
		return nil
	}
	return o.WarningAnomalyScore
}

func (o *SchemasWafFirewallVersionDataAttributes) GetXSSScoreThreshold() *int64 {
	if o == nil {
		return nil
	}
	return o.XSSScoreThreshold
}

type SchemasWafFirewallVersionData struct {
	Attributes *SchemasWafFirewallVersionDataAttributes `json:"attributes,omitempty"`
	// Resource type.
	Type *TypeWafFirewallVersion `default:"waf_firewall_version" json:"type"`
}

func (s SchemasWafFirewallVersionData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SchemasWafFirewallVersionData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SchemasWafFirewallVersionData) GetAttributes() *SchemasWafFirewallVersionDataAttributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *SchemasWafFirewallVersionData) GetType() *TypeWafFirewallVersion {
	if o == nil {
		return nil
	}
	return o.Type
}
