// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"Fastly/internal/utils"
)

type TLSActivationData struct {
	Relationships *RelationshipsForTLSActivationInput `json:"relationships,omitempty"`
	// Resource type.
	Type *TypeTLSActivation `default:"tls_activation" json:"type"`
}

func (t TLSActivationData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TLSActivationData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TLSActivationData) GetRelationships() *RelationshipsForTLSActivationInput {
	if o == nil {
		return nil
	}
	return o.Relationships
}

func (o *TLSActivationData) GetType() *TypeTLSActivation {
	if o == nil {
		return nil
	}
	return o.Type
}
