// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// TypeTLSSubscription - Resource type
type TypeTLSSubscription string

const (
	TypeTLSSubscriptionTLSSubscription TypeTLSSubscription = "tls_subscription"
)

func (e TypeTLSSubscription) ToPointer() *TypeTLSSubscription {
	return &e
}

func (e *TypeTLSSubscription) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tls_subscription":
		*e = TypeTLSSubscription(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeTLSSubscription: %v", v)
	}
}
