// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateWafActiveRuleRequest struct {
	BulkWafActiveRules *shared.BulkWafActiveRules `request:"mediaType=application/vnd.api+json"`
	// Alphanumeric string identifying a WAF Firewall.
	FirewallID string `pathParam:"style=simple,explode=false,name=firewall_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *CreateWafActiveRuleRequest) GetBulkWafActiveRules() *shared.BulkWafActiveRules {
	if o == nil {
		return nil
	}
	return o.BulkWafActiveRules
}

func (o *CreateWafActiveRuleRequest) GetFirewallID() string {
	if o == nil {
		return ""
	}
	return o.FirewallID
}

func (o *CreateWafActiveRuleRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type CreateWafActiveRuleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	WafActiveRuleCreationResponse *shared.WafActiveRuleCreationResponse
}

func (o *CreateWafActiveRuleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateWafActiveRuleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateWafActiveRuleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateWafActiveRuleResponse) GetWafActiveRuleCreationResponse() *shared.WafActiveRuleCreationResponse {
	if o == nil {
		return nil
	}
	return o.WafActiveRuleCreationResponse
}
