// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CreateTLSCertSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

// CreateTLSCert201ApplicationVndAPIPlusJSON - Created
type CreateTLSCert201ApplicationVndAPIPlusJSON struct {
}

type CreateTLSCertResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateTLSCert201ApplicationVndAPIPlusJSONObject *CreateTLSCert201ApplicationVndAPIPlusJSON
}
