// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateInvitationSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

func (o *CreateInvitationSecurity) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type CreateInvitationResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	InvitationResponse *shared.InvitationResponse
}

func (o *CreateInvitationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateInvitationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateInvitationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateInvitationResponse) GetInvitationResponse() *shared.InvitationResponse {
	if o == nil {
		return nil
	}
	return o.InvitationResponse
}
