// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateLogLogentriesSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

func (o *CreateLogLogentriesSecurity) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type CreateLogLogentriesRequest struct {
	LoggingLogentries3 *shared.LoggingLogentries3 `request:"mediaType=application/x-www-form-urlencoded"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *CreateLogLogentriesRequest) GetLoggingLogentries3() *shared.LoggingLogentries3 {
	if o == nil {
		return nil
	}
	return o.LoggingLogentries3
}

func (o *CreateLogLogentriesRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *CreateLogLogentriesRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type CreateLogLogentriesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LoggingLogentriesResponse *shared.LoggingLogentriesResponse
}

func (o *CreateLogLogentriesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLogLogentriesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLogLogentriesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateLogLogentriesResponse) GetLoggingLogentriesResponse() *shared.LoggingLogentriesResponse {
	if o == nil {
		return nil
	}
	return o.LoggingLogentriesResponse
}
