// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateDictionaryItemSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

func (o *CreateDictionaryItemSecurity) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type CreateDictionaryItemRequest struct {
	// Alphanumeric string identifying a Dictionary.
	DictionaryID   string                 `pathParam:"style=simple,explode=false,name=dictionary_id"`
	DictionaryItem *shared.DictionaryItem `request:"mediaType=application/x-www-form-urlencoded"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
}

func (o *CreateDictionaryItemRequest) GetDictionaryID() string {
	if o == nil {
		return ""
	}
	return o.DictionaryID
}

func (o *CreateDictionaryItemRequest) GetDictionaryItem() *shared.DictionaryItem {
	if o == nil {
		return nil
	}
	return o.DictionaryItem
}

func (o *CreateDictionaryItemRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

type CreateDictionaryItemResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	DictionaryItemResponse *shared.DictionaryItemResponse
}

func (o *CreateDictionaryItemResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDictionaryItemResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDictionaryItemResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateDictionaryItemResponse) GetDictionaryItemResponse() *shared.DictionaryItemResponse {
	if o == nil {
		return nil
	}
	return o.DictionaryItemResponse
}
