// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateLogDatadogRequest struct {
	LoggingDatadog3 *shared.LoggingDatadog3 `request:"mediaType=application/x-www-form-urlencoded"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *CreateLogDatadogRequest) GetLoggingDatadog3() *shared.LoggingDatadog3 {
	if o == nil {
		return nil
	}
	return o.LoggingDatadog3
}

func (o *CreateLogDatadogRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *CreateLogDatadogRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type CreateLogDatadogResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LoggingDatadogResponse *shared.LoggingDatadogResponse
}

func (o *CreateLogDatadogResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateLogDatadogResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateLogDatadogResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateLogDatadogResponse) GetLoggingDatadogResponse() *shared.LoggingDatadogResponse {
	if o == nil {
		return nil
	}
	return o.LoggingDatadogResponse
}
