// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type CreateWafActiveRulesTagSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type CreateWafActiveRulesTagRequest struct {
	// Alphanumeric string identifying a WAF Firewall.
	FirewallID string `pathParam:"style=simple,explode=false,name=firewall_id"`
	// Integer identifying a service version.
	VersionID          int64                      `pathParam:"style=simple,explode=false,name=version_id"`
	WafActiveRuleInput *shared.WafActiveRuleInput `request:"mediaType=application/vnd.api+json"`
	// Name of the tag.
	WafTagName string `pathParam:"style=simple,explode=false,name=waf_tag_name"`
}

type CreateWafActiveRulesTagResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
