// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeletePoolServerSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type DeletePoolServerRequest struct {
	// Alphanumeric string identifying a Pool.
	PoolID string `pathParam:"style=simple,explode=false,name=pool_id"`
	// Alphanumeric string identifying a Server.
	ServerID string `pathParam:"style=simple,explode=false,name=server_id"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
}

// DeletePoolServer200ApplicationJSON - OK
type DeletePoolServer200ApplicationJSON struct {
	// ok
	Status *string `json:"status,omitempty"`
}

type DeletePoolServerResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	DeletePoolServer200ApplicationJSONObject *DeletePoolServer200ApplicationJSON
}
