// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DisableProductSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type DisableProductRequest struct {
	ProductID string `pathParam:"style=simple,explode=false,name=product_id"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
}

type DisableProductResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
