// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type GetACLEntryRequest struct {
	// Alphanumeric string identifying an ACL Entry.
	ACLEntryID string `pathParam:"style=simple,explode=false,name=acl_entry_id"`
	// Alphanumeric string identifying a ACL.
	ACLID string `pathParam:"style=simple,explode=false,name=acl_id"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
}

func (o *GetACLEntryRequest) GetACLEntryID() string {
	if o == nil {
		return ""
	}
	return o.ACLEntryID
}

func (o *GetACLEntryRequest) GetACLID() string {
	if o == nil {
		return ""
	}
	return o.ACLID
}

func (o *GetACLEntryRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

type GetACLEntryResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	ACLEntryResponse *shared.ACLEntryResponse
}

func (o *GetACLEntryResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetACLEntryResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetACLEntryResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetACLEntryResponse) GetACLEntryResponse() *shared.ACLEntryResponse {
	if o == nil {
		return nil
	}
	return o.ACLEntryResponse
}
