// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type GetInvoiceSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type GetInvoiceRequest struct {
	// 2-digit month.
	Month string `pathParam:"style=simple,explode=false,name=month"`
	// 4-digit year.
	Year string `pathParam:"style=simple,explode=false,name=year"`
}

type GetInvoiceResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	BillingResponse *shared.BillingResponse
	// OK
	GetInvoice200ApplicationPdfBinaryString []byte
	// OK
	GetInvoice200TextCsvCsvString *string
}
