// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type GetLogLogshuttleSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

func (o *GetLogLogshuttleSecurity) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type GetLogLogshuttleRequest struct {
	// The name for the real-time logging configuration.
	LoggingLogshuttleName string `pathParam:"style=simple,explode=false,name=logging_logshuttle_name"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *GetLogLogshuttleRequest) GetLoggingLogshuttleName() string {
	if o == nil {
		return ""
	}
	return o.LoggingLogshuttleName
}

func (o *GetLogLogshuttleRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *GetLogLogshuttleRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type GetLogLogshuttleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LoggingLogshuttleResponse *shared.LoggingLogshuttleResponse
}

func (o *GetLogLogshuttleResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLogLogshuttleResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLogLogshuttleResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetLogLogshuttleResponse) GetLoggingLogshuttleResponse() *shared.LoggingLogshuttleResponse {
	if o == nil {
		return nil
	}
	return o.LoggingLogshuttleResponse
}
