// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type GetLogDigoceanRequest struct {
	// The name for the real-time logging configuration.
	LoggingDigitaloceanName string `pathParam:"style=simple,explode=false,name=logging_digitalocean_name"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *GetLogDigoceanRequest) GetLoggingDigitaloceanName() string {
	if o == nil {
		return ""
	}
	return o.LoggingDigitaloceanName
}

func (o *GetLogDigoceanRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *GetLogDigoceanRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type GetLogDigoceanResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LoggingDigitaloceanResponse *shared.LoggingDigitaloceanResponse
}

func (o *GetLogDigoceanResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetLogDigoceanResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetLogDigoceanResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetLogDigoceanResponse) GetLoggingDigitaloceanResponse() *shared.LoggingDigitaloceanResponse {
	if o == nil {
		return nil
	}
	return o.LoggingDigitaloceanResponse
}
