// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type GetRegionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	HistoricalRegionsResponse *shared.HistoricalRegionsResponse
}

func (o *GetRegionsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetRegionsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetRegionsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetRegionsResponse) GetHistoricalRegionsResponse() *shared.HistoricalRegionsResponse {
	if o == nil {
		return nil
	}
	return o.HistoricalRegionsResponse
}
