// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type ListWafRulesSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type ListWafRulesRequest struct {
	// Limit the returned rules to a specific ModSecurity rule ID.
	FilterModsecRuleID *string `queryParam:"style=form,explode=true,name=filter[modsec_rule_id]"`
	// Limit the returned rules to a set not included in the active firewall version for a firewall.
	FilterWafFirewallIDNotMatch *string `queryParam:"style=form,explode=true,name=filter[waf_firewall.id][not][match]"`
	// Limit the returned rules to a set linked to a source.
	FilterWafRuleRevisionsSource *string `queryParam:"style=form,explode=true,name=filter[waf_rule_revisions][source]"`
	// Limit the returned rules to a set linked to a tag by name.
	FilterWafTagsName *string `queryParam:"style=form,explode=true,name=filter[waf_tags][name]"`
	// Include relationships. Optional, comma-separated values. Permitted values: `waf_tags` and `waf_rule_revisions`.
	//
	Include *string `queryParam:"style=form,explode=true,name=include"`
	// Current page.
	PageNumber *int64 `queryParam:"style=form,explode=true,name=page[number]"`
	// Number of records per page.
	PageSize *int64 `queryParam:"style=form,explode=true,name=page[size]"`
}

type ListWafRulesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	WafRulesResponse *shared.WafRulesResponse
}
