// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type SetValueForKeySecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

type SetValueForKeyRequest struct {
	RequestBody       *string `request:"mediaType=application/octet-stream"`
	Add               *bool   `queryParam:"style=form,explode=true,name=add"`
	Append            *bool   `queryParam:"style=form,explode=true,name=append"`
	BackgroundFetch   *bool   `queryParam:"style=form,explode=true,name=background_fetch"`
	IfGenerationMatch *int64  `header:"style=simple,explode=false,name=if-generation-match"`
	KeyName           string  `pathParam:"style=simple,explode=false,name=key_name"`
	Metadata          *string `header:"style=simple,explode=false,name=metadata"`
	Prepend           *bool   `queryParam:"style=form,explode=true,name=prepend"`
	StoreID           string  `pathParam:"style=simple,explode=false,name=store_id"`
	TimeToLiveSec     *int64  `header:"style=simple,explode=false,name=time_to_live_sec"`
}

type SetValueForKeyResponse struct {
	ContentType string
	Headers     map[string][]string
	StatusCode  int
	RawResponse *http.Response
	// OK
	SetValueForKey200ApplicationOctetStreamByteString *string
}
