// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Fastly/pkg/models/shared"
	"net/http"
)

type UpdateLogSftpSecurity struct {
	Token string `security:"scheme,type=apiKey,subtype=header,name=Fastly-Key"`
}

func (o *UpdateLogSftpSecurity) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

type UpdateLogSftpRequest struct {
	LoggingSftpInput *shared.LoggingSftpInput `request:"mediaType=application/x-www-form-urlencoded"`
	// The name for the real-time logging configuration.
	LoggingSftpName string `pathParam:"style=simple,explode=false,name=logging_sftp_name"`
	// Alphanumeric string identifying the service.
	ServiceID string `pathParam:"style=simple,explode=false,name=service_id"`
	// Integer identifying a service version.
	VersionID int64 `pathParam:"style=simple,explode=false,name=version_id"`
}

func (o *UpdateLogSftpRequest) GetLoggingSftpInput() *shared.LoggingSftpInput {
	if o == nil {
		return nil
	}
	return o.LoggingSftpInput
}

func (o *UpdateLogSftpRequest) GetLoggingSftpName() string {
	if o == nil {
		return ""
	}
	return o.LoggingSftpName
}

func (o *UpdateLogSftpRequest) GetServiceID() string {
	if o == nil {
		return ""
	}
	return o.ServiceID
}

func (o *UpdateLogSftpRequest) GetVersionID() int64 {
	if o == nil {
		return 0
	}
	return o.VersionID
}

type UpdateLogSftpResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	LoggingSftpResponse *shared.LoggingSftpResponse
}

func (o *UpdateLogSftpResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *UpdateLogSftpResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *UpdateLogSftpResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *UpdateLogSftpResponse) GetLoggingSftpResponse() *shared.LoggingSftpResponse {
	if o == nil {
		return nil
	}
	return o.LoggingSftpResponse
}
