// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EnabledProductResponseLinks struct {
	// Location of resource
	Self *string `json:"self,omitempty"`
	// Location of the service resource
	Service *string `json:"service,omitempty"`
}

type EnabledProductResponseProduct struct {
	// Product identifier
	ID *string `json:"id,omitempty"`
	// Name of the object
	Object *string `json:"object,omitempty"`
}

type EnabledProductResponseService struct {
	// Service identifier
	ID *string `json:"id,omitempty"`
	// Name of the object
	Object *string `json:"object,omitempty"`
}

// EnabledProductResponse - OK
type EnabledProductResponse struct {
	Links   *EnabledProductResponseLinks   `json:"_links,omitempty"`
	Product *EnabledProductResponseProduct `json:"product,omitempty"`
	Service *EnabledProductResponseService `json:"service,omitempty"`
}
