// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenericTokenError - Missing or expired token.
type GenericTokenError struct {
	Msg *string `json:"msg,omitempty"`
}
