// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// HistoricalUsageServiceResponseMeta - Meta information about the scope of the query in a human readable format.
type HistoricalUsageServiceResponseMeta struct {
	By     *string `json:"by,omitempty"`
	From   *string `json:"from,omitempty"`
	Region *string `json:"region,omitempty"`
	To     *string `json:"to,omitempty"`
}

// HistoricalUsageServiceResponse - OK
type HistoricalUsageServiceResponse struct {
	Data *HistoricalUsageResults `json:"data,omitempty"`
	// Meta information about the scope of the query in a human readable format.
	Meta *HistoricalUsageServiceResponseMeta `json:"meta,omitempty"`
	// If the query was not successful, this will provide a string that explains why.
	Msg *string `json:"msg,omitempty"`
	// Whether or not we were able to successfully execute the query.
	Status *string `json:"status,omitempty"`
}
