// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type HistoricalUsageMonthResponseData struct {
	CustomerID *string                                      `json:"customer_id,omitempty"`
	Services   map[string]map[string]HistoricalUsageResults `json:"services,omitempty"`
	Total      *HistoricalUsageResults                      `json:"total,omitempty"`
}

// HistoricalUsageMonthResponseMeta - Meta information about the scope of the query in a human readable format.
type HistoricalUsageMonthResponseMeta struct {
	By     *string `json:"by,omitempty"`
	From   *string `json:"from,omitempty"`
	Region *string `json:"region,omitempty"`
	To     *string `json:"to,omitempty"`
}

// HistoricalUsageMonthResponse - OK
type HistoricalUsageMonthResponse struct {
	Data *HistoricalUsageMonthResponseData `json:"data,omitempty"`
	// Meta information about the scope of the query in a human readable format.
	Meta *HistoricalUsageMonthResponseMeta `json:"meta,omitempty"`
	// If the query was not successful, this will provide a string that explains why.
	Msg *string `json:"msg,omitempty"`
	// Whether or not we were able to successfully execute the query.
	Status *string `json:"status,omitempty"`
}
