// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MutualAuthenticationResponseData struct {
	Attributes    *MutualAuthenticationResponseAttributes `json:"attributes,omitempty"`
	ID            *string                                 `json:"id,omitempty"`
	Relationships interface{}                             `json:"relationships,omitempty"`
	// Resource type
	Type *TypeMutualAuthentication `json:"type,omitempty"`
}
