// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RelationshipMemberTLSConfigurationInput struct {
	// Resource type
	Type *TypeTLSConfiguration `json:"type,omitempty"`
}

type RelationshipMemberTLSConfiguration struct {
	ID *string `json:"id,omitempty"`
	// Resource type
	Type *TypeTLSConfiguration `json:"type,omitempty"`
}
