// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RelationshipWafFirewallVersionWafFirewallVersion struct {
	Data []RelationshipMemberWafFirewallVersion `json:"data,omitempty"`
}

type RelationshipWafFirewallVersion struct {
	WafFirewallVersion *RelationshipWafFirewallVersionWafFirewallVersion `json:"waf_firewall_version,omitempty"`
}

type RelationshipWafFirewallVersionWafFirewallVersionInput struct {
	Data []RelationshipMemberWafFirewallVersionInput `json:"data,omitempty"`
}

type RelationshipWafFirewallVersionInput struct {
	WafFirewallVersion *RelationshipWafFirewallVersionWafFirewallVersionInput `json:"waf_firewall_version,omitempty"`
}
