// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type RelationshipMemberTLSActivationInput struct {
	// Resource type.
	Type *TypeTLSActivation `json:"type,omitempty"`
}

type RelationshipMemberTLSActivation struct {
	ID *string `json:"id,omitempty"`
	// Resource type.
	Type *TypeTLSActivation `json:"type,omitempty"`
}
