// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// RoleUser - The permissions role assigned to the user. Can be `user`, `billing`, `engineer`, or `superuser`.
type RoleUser string

const (
	RoleUserUser      RoleUser = "user"
	RoleUserBilling   RoleUser = "billing"
	RoleUserEngineer  RoleUser = "engineer"
	RoleUserSuperuser RoleUser = "superuser"
)

func (e RoleUser) ToPointer() *RoleUser {
	return &e
}

func (e *RoleUser) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		fallthrough
	case "billing":
		fallthrough
	case "engineer":
		fallthrough
	case "superuser":
		*e = RoleUser(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RoleUser: %v", v)
	}
}
