// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// ServerResponse - OK
type ServerResponse struct {
	// A hostname, IPv4, or IPv6 address for the server. Required.
	Address *string `json:"address,omitempty"`
	// A freeform descriptive note.
	Comment *string `json:"comment,omitempty"`
	// Date and time in ISO 8601 format.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Date and time in ISO 8601 format.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Allows servers to be enabled and disabled in a pool.
	Disabled *bool   `json:"disabled,omitempty"`
	ID       *string `json:"id,omitempty"`
	// Maximum number of connections. If the value is `0`, it inherits the value from pool's `max_conn_default`.
	MaxConn *int64 `json:"max_conn,omitempty"`
	// The hostname to override the Host header. Defaults to `null` meaning no override of the Host header if not set. This setting can also be added to a Pool definition. However, the server setting will override the Pool setting.
	OverrideHost *string `json:"override_host,omitempty"`
	PoolID       *string `json:"pool_id,omitempty"`
	// Port number. Setting port `443` does not force TLS. Set `use_tls` in pool to force TLS.
	Port      *int64  `json:"port,omitempty"`
	ServiceID *string `json:"service_id,omitempty"`
	// Date and time in ISO 8601 format.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Weight (`1-100`) used to load balance this server against others.
	Weight *int64 `json:"weight,omitempty"`
}
