// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ServiceInvitationDataAttributesPermission - The permission the accepting user will have in relation to the service.
type ServiceInvitationDataAttributesPermission string

const (
	ServiceInvitationDataAttributesPermissionFull        ServiceInvitationDataAttributesPermission = "full"
	ServiceInvitationDataAttributesPermissionReadOnly    ServiceInvitationDataAttributesPermission = "read_only"
	ServiceInvitationDataAttributesPermissionPurgeSelect ServiceInvitationDataAttributesPermission = "purge_select"
	ServiceInvitationDataAttributesPermissionPurgeAll    ServiceInvitationDataAttributesPermission = "purge_all"
)

func (e ServiceInvitationDataAttributesPermission) ToPointer() *ServiceInvitationDataAttributesPermission {
	return &e
}

func (e *ServiceInvitationDataAttributesPermission) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full":
		fallthrough
	case "read_only":
		fallthrough
	case "purge_select":
		fallthrough
	case "purge_all":
		*e = ServiceInvitationDataAttributesPermission(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServiceInvitationDataAttributesPermission: %v", v)
	}
}

type ServiceInvitationDataAttributes struct {
	// The permission the accepting user will have in relation to the service.
	Permission *ServiceInvitationDataAttributesPermission `json:"permission,omitempty"`
}

// ServiceInvitationDataRelationshipsInput - Service the accepting user will have access to.
type ServiceInvitationDataRelationshipsInput struct {
	Service *RelationshipMemberServiceInput `json:"service,omitempty"`
}

type ServiceInvitationDataInput struct {
	Attributes *ServiceInvitationDataAttributes `json:"attributes,omitempty"`
	// Service the accepting user will have access to.
	Relationships *ServiceInvitationDataRelationshipsInput `json:"relationships,omitempty"`
	// Resource type
	Type *TypeServiceInvitation `json:"type,omitempty"`
}
