// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SettingsResponse - OK
type SettingsResponse struct {
	// The default host name for the version.
	GeneralDefaultHost *string `json:"general.default_host,omitempty"`
	// The default time-to-live (TTL) for the version.
	GeneralDefaultTTL *int64 `json:"general.default_ttl,omitempty"`
	// Enables serving a stale object if there is an error.
	GeneralStaleIfError *bool `json:"general.stale_if_error,omitempty"`
	// The default time-to-live (TTL) for serving the stale object for the version.
	GeneralStaleIfErrorTTL *int64  `json:"general.stale_if_error_ttl,omitempty"`
	ServiceID              *string `json:"service_id,omitempty"`
	Version                *int64  `json:"version,omitempty"`
}
