// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type StarResponseData struct {
	Attributes *Timestamps `json:"attributes,omitempty"`
	ID         *string     `json:"id,omitempty"`
}

// StarResponse - OK
type StarResponse struct {
	Data *StarResponseData `json:"data,omitempty"`
}
