// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TLSActivationResponse - Created
type TLSActivationResponse struct {
	Data *TLSActivationResponseData `json:"data,omitempty"`
}

func (o *TLSActivationResponse) GetData() *TLSActivationResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
