// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// TLSConfigurationResponse - OK
type TLSConfigurationResponse struct {
	Data *TLSConfigurationResponseData `json:"data,omitempty"`
}
