// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TLSDomainDataRelationships2TLSCertificates struct {
	Data []RelationshipMemberTLSCertificate `json:"data,omitempty"`
}

// TLSDomainDataRelationships2 - The list of all the [TLS certificates](#tls_certificates) that include this domain in their SAN list.
type TLSDomainDataRelationships2 struct {
	TLSCertificates *TLSDomainDataRelationships2TLSCertificates `json:"tls_certificates,omitempty"`
}

type TLSDomainDataRelationships1TLSActivations struct {
	Data []RelationshipMemberTLSActivation `json:"data,omitempty"`
}

// TLSDomainDataRelationships1 - The list of [TLS activations](#tls_activations) that exist for the domain. If empty, then this domain is not enabled to serve TLS traffic.
type TLSDomainDataRelationships1 struct {
	TLSActivations *TLSDomainDataRelationships1TLSActivations `json:"tls_activations,omitempty"`
}

type TLSDomainData struct {
	// The domain name.
	ID            *string     `json:"id,omitempty"`
	Relationships interface{} `json:"relationships,omitempty"`
	// Resource type
	Type *TypeTLSDomain `json:"type,omitempty"`
}
