// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TypeTLSDomain - Resource type
type TypeTLSDomain string

const (
	TypeTLSDomainTLSDomain TypeTLSDomain = "tls_domain"
)

func (e TypeTLSDomain) ToPointer() *TypeTLSDomain {
	return &e
}

func (e *TypeTLSDomain) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tls_domain":
		*e = TypeTLSDomain(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeTLSDomain: %v", v)
	}
}
