// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// TypeWafFirewallVersion - Resource type.
type TypeWafFirewallVersion string

const (
	TypeWafFirewallVersionWafFirewallVersion TypeWafFirewallVersion = "waf_firewall_version"
)

func (e TypeWafFirewallVersion) ToPointer() *TypeWafFirewallVersion {
	return &e
}

func (e *TypeWafFirewallVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "waf_firewall_version":
		*e = TypeWafFirewallVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeWafFirewallVersion: %v", v)
	}
}
