// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WafActiveRuleResponse - OK
type WafActiveRuleResponse struct {
	Data *WafActiveRuleResponseData `json:"data,omitempty"`
}
