// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// WafActiveRuleDataAttributesStatus - Describes the behavior for the particular rule revision within this firewall version.
type WafActiveRuleDataAttributesStatus string

const (
	WafActiveRuleDataAttributesStatusLog   WafActiveRuleDataAttributesStatus = "log"
	WafActiveRuleDataAttributesStatusBlock WafActiveRuleDataAttributesStatus = "block"
	WafActiveRuleDataAttributesStatusScore WafActiveRuleDataAttributesStatus = "score"
)

func (e WafActiveRuleDataAttributesStatus) ToPointer() *WafActiveRuleDataAttributesStatus {
	return &e
}

func (e *WafActiveRuleDataAttributesStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "log":
		fallthrough
	case "block":
		fallthrough
	case "score":
		*e = WafActiveRuleDataAttributesStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WafActiveRuleDataAttributesStatus: %v", v)
	}
}

type WafActiveRuleDataAttributes struct {
	// The ModSecurity rule ID of the associated rule revision.
	ModsecRuleID *int64                   `json:"modsec_rule_id,omitempty"`
	Revision     *WafRuleRevisionOrLatest `json:"revision,omitempty"`
	// Describes the behavior for the particular rule revision within this firewall version.
	Status *WafActiveRuleDataAttributesStatus `json:"status,omitempty"`
}

func (o *WafActiveRuleDataAttributes) GetModsecRuleID() *int64 {
	if o == nil {
		return nil
	}
	return o.ModsecRuleID
}

func (o *WafActiveRuleDataAttributes) GetRevision() *WafRuleRevisionOrLatest {
	if o == nil {
		return nil
	}
	return o.Revision
}

func (o *WafActiveRuleDataAttributes) GetStatus() *WafActiveRuleDataAttributesStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type WafActiveRuleData struct {
	Attributes    *WafActiveRuleDataAttributes `json:"attributes,omitempty"`
	Relationships interface{}                  `json:"relationships,omitempty"`
	// Resource type.
	Type *TypeWafActiveRule `json:"type,omitempty"`
}

func (o *WafActiveRuleData) GetAttributes() *WafActiveRuleDataAttributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *WafActiveRuleData) GetRelationships() interface{} {
	if o == nil {
		return nil
	}
	return o.Relationships
}

func (o *WafActiveRuleData) GetType() *TypeWafActiveRule {
	if o == nil {
		return nil
	}
	return o.Type
}

type WafActiveRuleDataInput struct {
	Attributes    *WafActiveRuleDataAttributes `json:"attributes,omitempty"`
	Relationships interface{}                  `json:"relationships,omitempty"`
	// Resource type.
	Type *TypeWafActiveRule `json:"type,omitempty"`
}

func (o *WafActiveRuleDataInput) GetAttributes() *WafActiveRuleDataAttributes {
	if o == nil {
		return nil
	}
	return o.Attributes
}

func (o *WafActiveRuleDataInput) GetRelationships() interface{} {
	if o == nil {
		return nil
	}
	return o.Relationships
}

func (o *WafActiveRuleDataInput) GetType() *TypeWafActiveRule {
	if o == nil {
		return nil
	}
	return o.Type
}
