// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WafFirewallResponse - Created
type WafFirewallResponse struct {
	Data     *WafFirewallResponseData    `json:"data,omitempty"`
	Included []SchemasWafFirewallVersion `json:"included,omitempty"`
}

func (o *WafFirewallResponse) GetData() *WafFirewallResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *WafFirewallResponse) GetIncluded() []SchemasWafFirewallVersion {
	if o == nil {
		return nil
	}
	return o.Included
}
