// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WafFirewallDataAttributesInput struct {
	// The status of the firewall.
	Disabled *bool `json:"disabled,omitempty"`
	// Name of the corresponding condition object.
	PrefetchCondition *string `json:"prefetch_condition,omitempty"`
	// Name of the corresponding response object.
	Response *string `json:"response,omitempty"`
}

type WafFirewallDataInput struct {
	Attributes *WafFirewallDataAttributesInput `json:"attributes,omitempty"`
	// Resource type.
	Type *TypeWafFirewall `json:"type,omitempty"`
}
