// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WafRuleRevisionResponse - OK
type WafRuleRevisionResponse struct {
	Data     *WafRuleRevisionResponseData `json:"data,omitempty"`
	Included []WafRule                    `json:"included,omitempty"`
}
